### ISSUE TITLE
子镜像启动占用内存过大问题

### ISSUE THREAD

**Issue by lujunGit** [jt-20180528/skate#2]

**Comment by lujunGit** [comment]
- （失败测试）经试验，使用在Dcokerfile中传递内存参数的方式，不正确，会导致无法启动容器：

> EVN p="-Xmxn=200m"

- （可行）在docker启动容器时配置：

> run -m 100m --name wp -d ...

or:

在docker-compose.yml中配置：
```
config-service:
  image: ${IMAGE_PREFIX}config-service:${SKATE_VERSION}
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
  ports:
   - 8888:8888
  mem_limit: 100m
  memswap_limit: 200m
```

限制可用的 swap 大小
强调一下 --memory-swap 是必须要与 --memory 一起使用的。

正常情况下， --memory-swap 的值包含容器可用内存和可用 swap。所以 --memory="300m" --memory-swap="1g" 的含义为：
容器可以使用 300M 的物理内存，并且可以使用 700M(1G -300M) 的 swap。--memory-swap 居然是容器可以使用的物理内存和可以使用的 swap 之和！

把 --memory-swap 设置为 0 和不设置是一样的，此时如果设置了 --memory，容器可以使用的 swap 大小为 --memory 值的两倍。

如果 --memory-swap 的值和 --memory 相同，则容器不能使用 swap
```

就可以了。
